initialize project. implement MVC structure. render components for testing
Nyorikenoichi/the-movie-search pull request #4
Opened 2021-11-04 16:21 UTC by Nyorikenoichi

2021-11-05 14:16 UTC, M-fil requested changes
На самом деле, мне очень нравится, как ты быстро развиваешься в JS и применяешь информацию, которую я тебе даю. Красава 🔥 

Сейчас же нужно пофиксить все замечания. Чтобы было легче проверять, рекомендую создать ветку от develop, в которой ты будешь фиксить мои замечания. 

Можно ее назвать с префиксом `fix/имя-ветки`. Такого в GitFlow нет, но так тоже можно делать 👍

2021-11-05 14:16 UTC, M-fil commented on src/controller/controller.ts
> +    this.favorites = this.favorites.filter((item) =>
Смотри, ты удаляешь элемент по значению title и year. Я думаю, ты сам понимаешь, что это плохо.

Элементы в списке нужно идентифицировать по id. И у тебя такой имеется
<img width="611" alt="Screenshot 2021-11-05 at 3 24 31 PM" src="https://user-images.githubusercontent.com/56369004/140509962-74121e6d-6c5f-4f43-826c-511c1da86b79.png">
.

2021-11-05 14:16 UTC, M-fil commented on src/controller/controller.ts
> +    this.addFilms();
Рекомендую сделать у контролера метод init и запихнуть туда всю логику для инициализации приложения.

Просто у тебя this.addFilms - асинхроная функция и для нее в лучшем случае нужен await. А асинхронный конструктор - какая-то хрень)

2021-11-05 14:16 UTC, M-fil commented on src/controller/controller.ts
> +    this.films = this.films.concat(await this.service.getData(this.currentSearchRequest, this.currentFilmsPage));
Лучше вынеси в отдельную переменную полученные данные из `await this.service.getData(this.currentSearchRequest, this.currentFilmsPage)`.

Так будет более читабельно

2021-11-05 14:16 UTC, M-fil commented on src/core/services/filmsService.ts
> +  public async getData(searchRequest: string, page: number): Promise<FilmModel[]> {
Кстати, getData - достаточно абстрактное название для функции. Назовии ее более подробно, чтобы было понятна, по каким параметрам мы получаем данные.

2021-11-05 14:16 UTC, M-fil commented on src/core/services/filmsService.ts
> +    this.repository = new FilmsRepository();
Repository стоит интегрировать через Dependency Injection. Рекомендую сделать это через конструктор

2021-11-05 14:16 UTC, M-fil commented on src/controller/controller.ts
> +  public films: FilmModel[];
fimls и favorites должны быть приватными.

2021-11-05 14:16 UTC, M-fil commented on src/core/components/filmListComponent.ts
> +  public static render(filmsList: FilmModel[], controller: Controller): HTMLUListElement {
Кстати, вот тебе и принцип разделения интерфейса из SOLID (буква I). Ты передаешь целый тип Controller, хотя из него ты используешь только favorites и несколько функций. Опять же, создавай узконаправленные интерфейсы, а не передавай целый класс со всеми данными.

2021-11-05 14:16 UTC, M-fil commented on src/core/components/filmListComponent.ts
> +          addToFavoritesButton.innerText = 'add';
Смотри, весь текст, который видит пользователь, стоит выносить в какие-то константы.

Для управления текстом уже давно придумали инструменты. Один из них - `i18n`. В нем ты создаешь json файлы с текстом и потом исопльзуешь ключи из этих json файлов в своем js коде.

Многие говорят, что `i18n` нужна только для переводов. Но на самом деле - нет. Главная фича этой либы - удобное управление текстом.

Поэтому подключи i18n и замени весь текст, который видит пользователь на экране, значениями из json файлов.

2021-11-05 14:16 UTC, M-fil commented on src/core/components/filmListComponent.ts
> +          addToFavoritesButton.innerText = 'add';
Кстати, innerText является устревшим способом. Лучше юзай textContent.

Рекомендую также почитать различие innerText и textConnect

2021-11-05 14:16 UTC, M-fil commented on src/core/components/filmListComponent.ts
> +        event.preventDefault();
Лучше пиши `event.preventDefault();` в самом начале.

2021-11-05 14:16 UTC, M-fil commented on src/core/components/filmListComponent.ts
> +      li.appendChild(document.createTextNode(film.getTitle()));
appendChild - устаревший. Юзай append либо prepend

2021-11-05 14:16 UTC, M-fil commented on src/core/components/filmListComponent.ts
> +      addToFavoritesButton.innerText = controller.favorites.some((item: FilmModel) =>
Старайся создавать побольше переменных. Это не очень читабельно, когда код иден в одну строку и затем переноситься еще на другие строки)

2021-11-05 14:16 UTC, M-fil commented on src/core/components/filmListComponent.ts
> +      const li = document.createElement('li');
li - не самое лучшее название для переменной. Называй более подробно, но не совсем поверхностно

2021-11-05 14:16 UTC, M-fil commented on .eslintrc.js
> +module.exports = {
Претензия #1. Почему ты все разрабатывал в develop. Нужно ведь создавать feature-ветки по GitFlow. Давай дальше только по GitFlow. Это очень важно

https://www.atlassian.com/ru/git/tutorials/comparing-workflows/gitflow-workflow

2021-11-05 14:16 UTC, M-fil commented on package.json
> +    "eslint": "npx eslint ./",
Лучше юзай следующую комманду для eslint.

`npx eslint --fix [путь_к_директории]`

2021-11-05 14:16 UTC, M-fil commented on src/controller/controller.ts
> +    this.service = new FilmsService();
Сервис стоит внедрять через конструктор Controller

2021-11-05 14:16 UTC, M-fil commented on src/controller/controller.ts
> +    this.service = new FilmsService();
Ну и тип у внедряемого сервиса будет `service: Service`. То есть тип - это твой абстрактный класс

2021-11-05 14:16 UTC, M-fil commented on src/core/components/searchLineComponent.ts
> +  static render(root: Element, controller: Controller): void {
Есть такой тип как `HTMLElement`. Лучше юзай его, а не Element

2021-11-05 14:16 UTC, M-fil commented on src/core/components/searchLineComponent.ts
> +  static render(root: Element, controller: Controller): void {
Та же самая ситуация с controller, как и в FilmListComponent. Исправляй :)

2021-11-05 14:16 UTC, M-fil commented on src/core/components/searchLineComponent.ts
> +    submit.setAttribute('value', 'send request');
`send request` должен быть в json-файле от i18n

2021-11-05 14:16 UTC, M-fil commented on src/core/components/searchLineComponent.ts
> +      const searchRequest: string = root.querySelector('input').value;
Не совсем корректно получить html-элемент по тегу. Ведь у тебя возможно будут еще input внутри формы. Можно делать следующим образом:

```
event.target['searchInput'] // твой input как HTMLElement.

'searchInput' - атрибут name у input. Можно засетать как search.setAttribute('name', 'searchInput');
```

2021-11-05 14:16 UTC, M-fil commented on src/core/components/searchLineComponent.ts
> +      event.preventDefault();
Опять же, пиши event.preventDefault() в самом начале твоего колбэка

2021-11-05 14:16 UTC, M-fil commented on src/core/components/searchLineComponent.ts
> +    root.appendChild(form);
Кстати, чтобы не передавать root, ты можешь просто вернуть html-элемент из функции (return form), а затем сделать append во View, либо где ты там его делаешь))

2021-11-05 14:16 UTC, M-fil commented on src/core/components/searchLineComponent.ts
> +    form.appendChild(search);
юзаем append

2021-11-05 14:16 UTC, M-fil commented on src/core/interfaces/film.ts
> +export default interface Film {
Лучше юзай обычный export. Можешь почитать про их различия

https://learn.javascript.ru/import-export

2021-11-05 14:16 UTC, M-fil commented on src/core/interfaces/filmRequestResult.ts
> +import Film from './film';
Не всегда 1 файл - 1 интерфес. Можно в один файл добавлять интерфейсы, схожие по применению и логику.

Как раз именно для этого удобно использовать обычный export

2021-11-05 14:16 UTC, M-fil commented on src/core/repos/filmsRepository.ts
> +  protected getUrl(searchRequest: string, page: number): string {
getUrl - как то не очень. У тебя ведь в будущем возможно будет больше url, а не один.

Я обычно делаю так:
```
  protected static Urls = {
    MainUrl: (searchRequest: string, page: number) => `https://www.omdbapi.com/?s=${searchRequest}&apikey=9b67fc54&page=${page}`,
  }
```

2021-11-05 14:16 UTC, M-fil commented on src/core/repos/filmsRepository.ts
> +  public async getData(searchRequest: string, page: number): Promise<{ error?: string; Search?: Film[] }> {
Опять же, getData - очень поверхностное и абсрактное название. Назови более подробно

2021-11-05 14:16 UTC, M-fil commented on src/core/repos/filmsRepository.ts
> +  public async getData(searchRequest: string, page: number): Promise<{ error?: string; Search?: Film[] }> {
Кстати, насчет типов. У тебя ведь есть ResponseError, который стоило бы заюзать. Можно создать новый интерфейс для `{ error?: string; Search?: Film[] }`, используя ResponseError.

Я сделал так. Понимаю, многое не понятно, поэтому даю ссылки "на почитать"

1. https://www.typescriptlang.org/docs/handbook/utility-types.html#partialtype
2. https://www.typescriptlang.org/docs/handbook/2/objects.html

```
interface GetFilmsResults extends Partial<ResponseError> {
  Search?: Film[]
}
```

2021-11-05 14:16 UTC, M-fil commented on src/core/repos/filmsRepository.ts
> +  // eslint-disable-next-line consistent-return
Также этот коммент не нужен

2021-11-05 14:16 UTC, M-fil commented on src/core/repos/repository.ts
> +  public abstract getData(searchRequest: string, page: number): Promise<any>;
any мы не используем :)

2021-11-05 14:16 UTC, M-fil commented on src/core/repos/repository.ts
> +export default abstract class Repository {
Кстати, а почему у нас 12 ошибок eslin
<img width="623" alt="Screenshot 2021-11-05 at 4 35 52 PM" src="https://user-images.githubusercontent.com/56369004/140518818-d30e95eb-1010-42ef-b0a5-354c89562d0e.png">
t?

Ты забыл добавть комманду для lint-staged в .husky/pre-commit. Поэтому оно у тебя не чекало ошибку

2021-11-05 14:16 UTC, M-fil commented on src/core/repos/repository.ts
> +  public abstract getData(searchRequest: string, page: number): Promise<any>;
Добавь это правило в eslint:

```
'no-explicit-any': 'error',
```

2021-11-05 14:16 UTC, M-fil commented on src/index.ts
> +root.appendChild(searchDiv);
А зачем ты вставляешь эти div-ы здесь? Ты же можешь это делать в самих вьюхах. 

Тебе в router нужно интегрировать через конструктор только root. Дальше внутри router ты вставляешь нужную тебе страницу в root.

Поэтому эти блоки filmListDiv, favoritesDiv должны быть только во вьюхах

2021-11-05 14:16 UTC, M-fil commented on src/index.ts
> +const router = new Router(filmListView, favoritesView, filmListDiv, favoritesDiv);
А вот именно здесь нужно вставлять root (в конструктор Router).

2021-11-05 14:16 UTC, M-fil commented on src/index.ts
> +filmListView.setController(controller);
setContoller должен быть у router. Воспримиай router тоже как вьюху. Просто эта вьюха управляет другими вьюхами.

2021-11-05 14:16 UTC, M-fil commented on src/index.ts
> +filmListView.setController(controller);
Если тебе так нужно сетать контролер для определнной View, то делай это внутри router.

`filmListView.setController(controller);`

2021-11-05 14:16 UTC, M-fil commented on src/index.ts
> +SearchLineComponent.render(searchDiv, controller);
SearchLineComponent ты должен рендерить внутри View либо внутри Router

2021-11-05 14:16 UTC, M-fil commented on src/models/filmModel.ts
> +    this.imdbID = imdbID;
Мне кажется, ты забыл где-то засетать imdbID.
<img width="574" alt="Screenshot 2021-11-05 at 5 05 06 PM" src="https://user-images.githubusercontent.com/56369004/140523117-bea64e84-5e7c-485b-803d-752337b00b87.png">

2021-11-05 14:16 UTC, M-fil commented on src/views/favoritesView.ts
> +  public hide(root: Element): void {
Эту функцию круто бы вынести в Router либо в абстракнтый класс View

2021-11-05 14:16 UTC, M-fil commented on src/views/filmsListView.ts
> +/* eslint-disable no-param-reassign */
Этот коммент - плохо :) Стоит удалить

2021-11-05 14:16 UTC, M-fil commented on src/views/filmsListView.ts
> +    root.innerHTML = '';
Для этого сделай функцию hide в классе View

`root.innerHTML = '';`

2021-11-05 14:16 UTC, M-fil commented on src/views/filmsListView.ts
> +    loadMoreButton.addEventListener('mousedown', (event) => {
Тип для event тоже нужно указывать

2021-11-05 14:16 UTC, M-fil commented on src/core/view.ts
> +  protected controller: Controller;
Сюда стоит добавить protected root. Так будет намного легче развивать свою логику для любой View

2021-11-05 14:16 UTC, M-fil commented on src/core/services/service.ts
> +  public abstract getData(searchRequest: string, page: number): Promise<any>;
Никаких any в TS :)

2021-11-05 14:16 UTC, M-fil commented on src/core/services/filmsService.ts
> +      // will modify this later
Лучше сразу обрабатывай ошибку. Потом закалебешься интегировать ее во все части кода. Стоит ее возвращать в Contoller как тип ResponseError

2021-11-05 14:16 UTC, M-fil commented on src/core/router.ts
> +    // this.errorView.render()
Таких комментариев не должно быть в PR. В PR должен быть чистый код, без ошибок eslint и без лишних комментариев

2021-11-05 14:16 UTC, M-fil commented on src/core/router.ts
> +    this.favoritesView = favoritesView;
Это удаляем. Не очень хорошая логику, объяснял в других комментах этого PR.

```
    this.filmsListDiv = filmsListDiv;
    this.favoritesDiv = favoritesDiv;
```

2021-11-05 14:16 UTC, M-fil commented on src/core/router.ts
> +  private filmsListDiv: Element;
HTMLElement

2021-11-05 14:16 UTC, M-fil commented on .husky/pre-commit
> +
Добавь `npx lint-staged`

2021-11-09 12:58 UTC, Nyorikenoichi commented on src/core/services/filmsService.ts
> +    this.repository = new FilmsRepository();
repository должен быть внутри controller?

2021-11-18 14:02 UTC, closed without merging